export default {
    BU: {
        Code: 'BU',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    FU: {
        Code: 'FU',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    AL: {
        Code: 'AL',
        夜盘: true,
        交易所: 'sh',
        一手单位: 5,
    },
    CU: {
        Code: 'CU',
        夜盘: true,
        交易所: 'sh',
        一手单位: 5,
    },
    RU: {
        Code: 'RU',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    AU: {
        Code: 'AU',
        夜盘: true,
        交易所: 'sh',
        一手单位: 1000,
    },
    AG: {
        Code: 'AG',
        夜盘: true,
        交易所: 'sh',
        一手单位: 15,
    },
    RB: {
        Code: 'RB',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    HC: {
        Code: 'HC',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    A: {
        Code: 'A',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    B: {
        Code: 'B',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    M: {
        Code: 'M',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    C: {
        Code: 'C',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    Y: {
        Code: 'Y',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    L: {
        Code: 'L',
        夜盘: true,
        交易所: 'sh',
        一手单位: 5,
    },
    P: {
        Code: 'P',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    V: {
        Code: 'V',
        夜盘: true,
        交易所: 'sh',
        一手单位: 5,
    },
    PP: {
        Code: 'PP',
        夜盘: true,
        交易所: 'sh',
        一手单位: 5,
    },
    CS: {
        Code: 'CS',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    CF: {
        Code: 'CF',
        夜盘: true,
        交易所: 'sh',
        一手单位: 5,
    },
    SR: {
        Code: 'SR',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    TA: {
        Code: 'TA',
        夜盘: true,
        交易所: 'sh',
        一手单位: 5,
    },
    OI: {
        Code: 'OI',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    MA: {
        Code: 'MA',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    RM: {
        Code: 'RM',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
    AP: {
        Code: 'AP',
        夜盘: true,
        交易所: 'sh',
        一手单位: 10,
    },
}
